# Usa un'immagine di base Python ufficiale
FROM python:3.11-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file del progetto nella directory di lavoro
COPY . .

# Installa le dipendenze specificate in requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt

# Espone la porta 5000
EXPOSE 5000

# Comando di default: avvia server.py
CMD ["python", "server.py"]